### ISSUE TITLE
SQL Injection 

### ISSUE THREAD

**Issue by jessereitsma** [HetIsNiels/Glybe#1]
Hi,

I found a security issue in `/src/content/heading.php` on line 4 and 5
[heading.php#L4-L5](https://github.com/HetIsNiels/Glybe/blob/master/src/content/heading.php#L4-L5)

since ```$_SERVER['HTTP_USER_AGENT']``` is an user input the user can easily inject the query and getting access to the whole database.

******
#### Please, do **NOT** use this source without fixing this serious security issue.
******

Regards,
Jesse

**Comment by smiegles** [comment]
Hi,

This one is indeed very nasty, for the person who wrote this line of code, remind:
1. Don't access the super global variable $_SERVER (and $_GET, AND $_POST AND $_COOKIE) directly. Use some filtering functions instead, this will make sure that you can't make stupid mistakes like this.

@jessereitsma For now I would suggest to use `Glybe::Security()`

Regards,

Olivier

**Comment by jessereitsma** [comment]
Oh and maybe, you can remove a database-password left-over in the source.
[/src/includes/cron/bavaria_server.php#L2](https://github.com/HetIsNiels/Glybe/blob/master/src/includes/cron/bavaria_server.php#L2)

You welcome :smile:

**Comment by jessereitsma** [comment]
@Smiegles yes, adding `Glybe::Security()` should do the trick.

**Comment by HetIsNiels** [comment]
Fix has been merged, thanks.
